Feature/daiki kazusaki/edit environment.py
DaikiKazusaki/SemiB pull request #3
Opened 2024-12-21 08:10 UTC by DaikiKazusaki

# 変更したメソッド
- `step(self, action)`
- `is_valid_move(self, i, j, k, player)`
- `place_disc(self, i, j, k, player)`

# 変更内容

## stepメソッド
### 内容
- 3次元空間の座標を決める変数i, j, kを決定
- その他は変化なし
### 引数，返り値
- 引数
  - self：盤面の情報
  - action：0~63の変数，盤面のすべての点を網羅するように設計されている
- 返り値
  - 元のReversiEnv.pyと同じ

## is_valid_moveメソッド
### 引数，返り値
- 引数
  -  self：盤面の情報
  - i, j, k：3次元の座標
  - player：手番の色
- 返り値
  - True：(i, j, k)に石を配置可能
  - False：(i, j, k)に石を配置不可
### 内容
- 以下の場合は盤面に配置不可
  - (i, j, k)がボード外
  - (i, j, k)にすでに石が置かれている場合

## place_discメソッド
### 引数，返り値
- 引数
  - self：盤面の情報
  - i, j, k：3次元の座標
  - player：手番を表す．黒=1，白=-1
 - 返り値：なし
### 内容
- 石を座標(i, j, k)に配置する
- playerで手番の色が分かるので，これを代入する
- オセロでは石を反転する処理が必要だが，立体四目並べでは石を置くだけでよいので，反転処理は削除した

2024-12-21 08:14 UTC, DaikiKazusaki commented
aaa

2024-12-25 21:45 UTC, tkgpoyo requested changes
2つほどコメントしたので確認お願いします！

2024-12-25 21:45 UTC, tkgpoyo commented on Main/Environment.py
> +        # ひっくり返せる石があるか確認
is_valid_moveメソッド(81行目以降)について
オセロのルールが残っているんかな、多分この条件はいらないと思う！

2024-12-25 21:45 UTC, tkgpoyo commented on Main/Environment.py
> +        # actionは0~63の整数, これをボード上の(i,j,k)にマッピング
できれば、このaction(0〜63の数値)と座標((i, j, k))の対応がパッと見れる図を作って欲しいです！
めっちゃ簡単でいいです！

2024-12-26 00:28 UTC, DaikiKazusaki commented on Main/Environment.py
> +        # ひっくり返せる石があるか確認
確かに，なくても良さそうやな
消しときまーす

2024-12-26 00:29 UTC, DaikiKazusaki commented on Main/Environment.py
> +        # actionは0~63の整数, これをボード上の(i,j,k)にマッピング
今見たら，i, j, kの設定がちょっとミスってる気がするから，変更するわ
もう一回Pull Request送るわ

2024-12-26 00:42 UTC, DaikiKazusaki commented
# 変更点
- is_valid_moveメソッドの81行目以降を削除
- stepメソッドのi, j, kの定義変更

# i, j, kについて
基本的には，
- i：x座標
- j：y座標
- k：z座標

になるようにしてる．i, jは写真みたいなイメージで，kは高さになるから，actionを16で割ったときの商と一致するかな
![S__3735583](https://github.com/user-attachments/assets/8afb3f9b-f78b-4165-a66b-d9a430b98d49)

2024-12-26 00:48 UTC, tkgpoyo commented
> # 変更点
> 
> - is_valid_moveメソッドの81行目以降を削除
> 
> - stepメソッドのi, j, kの定義変更
> 
> 
> 
> # i, j, kについて
> 
> 基本的には，
> 
> - i：x座標
> 
> - j：y座標
> 
> - k：z座標
> 
> 
> 
> になるようにしてる．i, jは写真みたいなイメージで，kは高さになるから，actionを16で割ったときの商と一致するかな
> 
> ![S__3735583](https://github.com/user-attachments/assets/8afb3f9b-f78b-4165-a66b-d9a430b98d49)
> 
> 

変更確認しました！
大丈夫だと思います、わかりやすい図もつけてくれてありがとう！

2024-12-26 00:49 UTC, merged